<?php

declare(strict_types=1);

/**
 * SiteWatch installation wizard.
 *
 * Steps: 1 Requirements → 2 Database → 3 Tables → 4 Admin account → 5 Application settings → 6 Complete
 * Creates storage/install.lock when finished. Delete that file to run the installer again.
 */

define('SW_INSTALLER', true);
require __DIR__ . '/bootstrap.php';

use App\Core\App;
use App\Core\Crypto;
use App\Core\Database;
use App\Core\Request;
use App\Core\Response;
use App\Core\Validator;
use App\Repositories\SettingsRepository;
use App\Repositories\UserRepository;

$root = __DIR__;
$lockFile = $root . '/storage/install.lock';
$session = App::session();
$csrf = App::csrf();
$nonce = defined('SW_CSP_NONCE') ? SW_CSP_NONCE : '';
$baseUrl = App::detectBaseUrl();

$state = $session->get('_install', []);
if (!is_array($state)) {
    $state = [];
}
$step = max(1, min(6, (int) ($_GET['step'] ?? $state['step'] ?? 1)));
$errors = [];
$notice = null;

$installed = is_file($lockFile);
$maxReached = (int) ($state['step'] ?? 1);
if (!$installed && $step > $maxReached) {
    $step = $maxReached;
}

// ---------------------------------------------------------------------------
// Requirement checks
// ---------------------------------------------------------------------------
$requirements = [];
$requirements[] = ['PHP 8.2 or newer', PHP_VERSION, version_compare(PHP_VERSION, '8.2.0', '>=') ? 'ok' : 'bad'];
foreach (['pdo' => 'PDO', 'pdo_mysql' => 'PDO MySQL', 'curl' => 'cURL', 'openssl' => 'OpenSSL', 'json' => 'JSON', 'mbstring' => 'mbstring'] as $ext => $label) {
    $requirements[] = [$label . ' extension', extension_loaded($ext) ? 'loaded' : 'missing', extension_loaded($ext) ? 'ok' : 'bad'];
}
$requirements[] = ['intl extension (optional, for international domains)', extension_loaded('intl') ? 'loaded' : 'missing', extension_loaded('intl') ? 'ok' : 'warn'];
$requirements[] = ['Composer dependencies (vendor/)', is_file($root . '/vendor/autoload.php') ? 'installed' : 'missing — run composer install', is_file($root . '/vendor/autoload.php') ? 'ok' : 'bad'];
foreach (['storage', 'storage/logs', 'storage/cache', 'storage/locks'] as $dir) {
    $path = $root . '/' . $dir;
    if (!is_dir($path)) {
        @mkdir($path, 0755, true);
    }
    $requirements[] = [$dir . '/ writable', is_writable($path) ? 'writable' : 'not writable', is_writable($path) ? 'ok' : 'bad'];
}
$envWritable = is_file($root . '/.env') ? is_writable($root . '/.env') : is_writable($root);
$requirements[] = ['.env writable', $envWritable ? 'yes' : 'no — create .env manually from .env.example', $envWritable ? 'ok' : 'warn'];
$requirements[] = ['allow_url_fopen / cURL SSL', (curl_version()['ssl_version'] ?? '') !== '' ? curl_version()['ssl_version'] : 'no SSL support in cURL', (curl_version()['ssl_version'] ?? '') !== '' ? 'ok' : 'bad'];
$requirementsOk = !in_array('bad', array_column($requirements, 2), true);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
$dbConfig = static function (array $s): array {
    return [
        'host'     => (string) ($s['db']['host'] ?? '127.0.0.1'),
        'port'     => (int) ($s['db']['port'] ?? 3306),
        'name'     => (string) ($s['db']['name'] ?? 'sitewatch'),
        'user'     => (string) ($s['db']['user'] ?? ''),
        'password' => (string) ($s['db']['password'] ?? ''),
        'charset'  => 'utf8mb4',
        'options'  => [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false],
    ];
};

$envValue = static function (string $value): string {
    if ($value === '' || preg_match('/^[A-Za-z0-9_\-.:\/+=@]+$/', $value)) {
        return $value;
    }
    return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
};

$writeEnv = static function (array $s, string $appKey) use ($root, $envValue): void {
    $lines = [
        '# SiteWatch environment configuration — generated by install.php on ' . gmdate('Y-m-d H:i:s') . ' UTC',
        'APP_ENV=production',
        'APP_DEBUG=false',
        'APP_URL=' . $envValue((string) ($s['app']['url'] ?? '')),
        'APP_TIMEZONE=' . $envValue((string) ($s['app']['timezone'] ?? 'Asia/Karachi')),
        'APP_KEY=' . $envValue($appKey),
        '',
        'DB_HOST=' . $envValue((string) $s['db']['host']),
        'DB_PORT=' . $envValue((string) $s['db']['port']),
        'DB_NAME=' . $envValue((string) $s['db']['name']),
        'DB_USER=' . $envValue((string) $s['db']['user']),
        'DB_PASSWORD=' . $envValue((string) $s['db']['password']),
        '',
        'SESSION_LIFETIME=480',
        'LOGIN_MAX_ATTEMPTS=5',
        'LOGIN_LOCKOUT_MINUTES=15',
        'LOG_LEVEL=info',
        'LOG_MAX_FILES=14',
        '',
        '# SSRF protection: keep false unless you intentionally monitor private/internal websites',
        'MONITOR_ALLOW_PRIVATE=false',
        'MONITOR_MAX_PER_RUN=300',
        '',
    ];
    if (is_file($root . '/.env')) {
        @copy($root . '/.env', $root . '/.env.backup-' . gmdate('YmdHis'));
    }
    if (file_put_contents($root . '/.env', implode("\n", $lines)) === false) {
        throw new RuntimeException('Unable to write the .env file. Check directory permissions.');
    }
};

// ---------------------------------------------------------------------------
// Handle POST
// ---------------------------------------------------------------------------
if (Request::isPost() && !$installed) {
    if (!$csrf->validateRequest()) {
        $errors['_'] = 'Your session expired. Please try again.';
    } else {
        $action = (string) ($_POST['action'] ?? '');
        try {
            if ($action === 'requirements') {
                if (!$requirementsOk) {
                    $errors['_'] = 'Please resolve the failed requirements before continuing.';
                } else {
                    $state['step'] = 2;
                    $step = 2;
                }
            } elseif ($action === 'database') {
                $v = new Validator($_POST);
                $v->required('db_host', 'Host')->required('db_name', 'Database name')->required('db_user', 'Username')->integer('db_port', 1, 65535, 'Port');
                $v->regex('db_name', '/^[A-Za-z0-9_\-]+$/', 'Database name may only contain letters, numbers, - and _.');
                if ($v->fails()) {
                    $errors = $v->errors();
                } else {
                    $state['db'] = [
                        'host'     => trim((string) $_POST['db_host']),
                        'port'     => (int) ($_POST['db_port'] ?: 3306),
                        'name'     => trim((string) $_POST['db_name']),
                        'user'     => trim((string) $_POST['db_user']),
                        'password' => (string) ($_POST['db_password'] ?? ''),
                    ];
                    $config = $dbConfig($state);
                    $create = !empty($_POST['db_create']);
                    try {
                        $pdo = Database::connect($config, true);
                    } catch (Throwable $e) {
                        if ($create && (str_contains($e->getMessage(), 'Unknown database') || str_contains($e->getMessage(), '1049'))) {
                            $server = Database::connect($config, false);
                            $server->exec('CREATE DATABASE `' . str_replace('`', '', $config['name']) . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
                            $pdo = Database::connect($config, true);
                        } else {
                            throw $e;
                        }
                    }
                    $version = (string) $pdo->getAttribute(PDO::ATTR_SERVER_VERSION);
                    $state['db_version'] = $version;
                    $state['step'] = 3;
                    $step = 3;
                    $notice = 'Connected to MySQL/MariaDB ' . $version . '.';
                }
            } elseif ($action === 'tables') {
                $config = $dbConfig($state);
                $pdo = Database::connect($config, true);
                $sql = (string) file_get_contents($root . '/database/schema.sql');
                if ($sql === '') {
                    throw new RuntimeException('database/schema.sql is missing.');
                }
                $pdo->exec($sql);
                $tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
                $state['tables'] = count($tables);
                $state['step'] = 4;
                $step = 4;
                $notice = count($tables) . ' tables are ready.';
            } elseif ($action === 'admin') {
                $v = new Validator($_POST);
                $v->required('admin_name', 'Name')->max('admin_name', 100, 'Name');
                $v->required('admin_email', 'Email')->email('admin_email', 'Email');
                $v->required('admin_password', 'Password')->min('admin_password', 10, 'Password');
                if (($_POST['admin_password'] ?? '') !== ($_POST['admin_password_confirmation'] ?? '')) {
                    $v->addError('admin_password_confirmation', 'The password confirmation does not match.');
                }
                if ($v->fails()) {
                    $errors = $v->errors();
                } else {
                    $state['admin'] = ['name' => trim((string) $_POST['admin_name']), 'email' => mb_strtolower(trim((string) $_POST['admin_email'])), 'password' => (string) $_POST['admin_password']];
                    $state['step'] = 5;
                    $step = 5;
                }
            } elseif ($action === 'settings') {
                $v = new Validator($_POST);
                $v->required('app_name', 'Application name')->max('app_name', 100, 'Application name');
                $v->required('app_url', 'Application URL')->url('app_url', 'Application URL');
                $v->required('app_timezone', 'Timezone')->timezone('app_timezone', 'Timezone');
                $v->in('default_check_interval', [1, 2, 5, 10, 15, 30], 'Default interval');
                if ($v->fails()) {
                    $errors = $v->errors();
                } else {
                    $state['app'] = [
                        'name'     => trim((string) $_POST['app_name']),
                        'url'      => rtrim(trim((string) $_POST['app_url']), '/'),
                        'timezone' => (string) $_POST['app_timezone'],
                        'interval' => (int) ($_POST['default_check_interval'] ?? 5),
                    ];

                    // ---- Finish installation ----
                    $config = $dbConfig($state);
                    $db = new Database($config);
                    $appKey = Crypto::generateKey();
                    $writeEnv($state, $appKey);

                    $users = new UserRepository($db);
                    $existing = $users->findByEmail($state['admin']['email']);
                    if ($existing === null) {
                        $users->create($state['admin']['name'], $state['admin']['email'], $state['admin']['password']);
                    } else {
                        $users->updatePassword((int) $existing['id'], $state['admin']['password']);
                        $users->updateProfile((int) $existing['id'], $state['admin']['name'], $state['admin']['email']);
                    }

                    $settings = new SettingsRepository($db);
                    $settings->setMany([
                        'app_name'               => $state['app']['name'],
                        'app_url'                => $state['app']['url'],
                        'app_timezone'           => $state['app']['timezone'],
                        'default_check_interval' => $state['app']['interval'],
                    ]);

                    $db->insert('activity_logs', [
                        'action'      => 'settings.changed',
                        'description' => 'SiteWatch installed',
                        'created_at'  => gmdate('Y-m-d H:i:s'),
                    ]);

                    file_put_contents($lockFile, "installed " . gmdate('Y-m-d H:i:s') . " UTC\n");
                    $state['step'] = 6;
                    $step = 6;
                    $installed = true;
                    unset($state['admin']['password'], $state['db']['password']);
                }
            } elseif ($action === 'back') {
                $target = max(1, (int) ($_POST['target'] ?? 1));
                $state['step'] = min($target, (int) ($state['step'] ?? 1));
                $step = $target;
            }
        } catch (Throwable $e) {
            $errors['_'] = $e->getMessage();
        }
    }
    $session->set('_install', $state);
}

$s = $state;
$detectedUrl = $s['app']['url'] ?? $baseUrl;
$cronPath = str_replace('\\', '/', $root) . '/cron/monitor.php';
$steps = ['Requirements', 'Database', 'Tables', 'Admin', 'Settings', 'Complete'];
$appName = $s['app']['name'] ?? 'SiteWatch';
require __DIR__ . '/includes/brand.php';
?>
<!doctype html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title>Install · SiteWatch</title>
    <link rel="icon" href="<?= e($baseUrl . '/assets/images/favicon.svg') ?>" type="image/svg+xml">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="<?= e($baseUrl . '/assets/css/app.css') ?>" rel="stylesheet">
    <script nonce="<?= e($nonce) ?>">(function(){try{var t=localStorage.getItem('sw-theme');if(t!=='dark'&&t!=='light'){t=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}document.documentElement.setAttribute('data-bs-theme',t);}catch(e){}})();</script>
</head>
<body class="sw-body">
<div class="auth-page" style="align-items:flex-start;padding-top:48px">
    <div class="auth-shell" style="max-width:720px">
        <div class="auth-logo"><?= sw_brand_logo(200) ?></div>
        <div class="auth-card">
            <p class="lead-text mb-4">Installer</p>

        <?php if ($installed && $step !== 6): ?>
            <h1>Already installed</h1>
            <p class="lead-text">SiteWatch is installed and locked. To run the installer again, delete <span class="code-inline">storage/install.lock</span> on the server.</p>
            <a href="<?= e($baseUrl . '/login.php') ?>" class="btn btn-primary">Go to sign in</a>
        <?php else: ?>
            <div class="install-steps">
                <?php foreach ($steps as $i => $label): $n = $i + 1; ?>
                    <div class="step <?= $n === $step ? 'active' : ($n < $step ? 'done' : '') ?>"><?= $n ?>. <?= e($label) ?></div>
                <?php endforeach; ?>
            </div>

            <?php if (isset($errors['_'])): ?><div class="alert alert-danger"><i class="bi bi-exclamation-circle me-1"></i><?= e($errors['_']) ?></div><?php endif; ?>
            <?php if ($notice !== null): ?><div class="alert alert-success"><i class="bi bi-check-circle me-1"></i><?= e($notice) ?></div><?php endif; ?>

            <?php if ($step === 1): ?>
                <h1>Requirements</h1>
                <p class="lead-text">Checking that this server can run SiteWatch.</p>
                <ul class="req-list mb-4">
                    <?php foreach ($requirements as [$label, $value, $status]): ?>
                        <li><span><?= e($label) ?></span><span class="<?= e($status) ?>"><i class="bi <?= $status === 'ok' ? 'bi-check-circle-fill' : ($status === 'warn' ? 'bi-exclamation-triangle-fill' : 'bi-x-circle-fill') ?> me-1"></i><?= e($value) ?></span></li>
                    <?php endforeach; ?>
                </ul>
                <form method="post"><?= $csrf->field() ?><input type="hidden" name="action" value="requirements">
                    <button type="submit" class="btn btn-primary btn-lg w-100" <?= $requirementsOk ? '' : 'disabled' ?>>Continue</button>
                </form>

            <?php elseif ($step === 2): ?>
                <h1>Database</h1>
                <p class="lead-text">Enter the MySQL / MariaDB connection details. The user needs full privileges on the database.</p>
                <form method="post" novalidate><?= $csrf->field() ?><input type="hidden" name="action" value="database">
                    <div class="row g-3">
                        <div class="col-md-8"><label class="form-label">Host</label><input type="text" class="form-control<?= isset($errors['db_host']) ? ' is-invalid' : '' ?>" name="db_host" value="<?= e($s['db']['host'] ?? '127.0.0.1') ?>"><div class="invalid-feedback"><?= e($errors['db_host'] ?? '') ?></div></div>
                        <div class="col-md-4"><label class="form-label">Port</label><input type="number" class="form-control<?= isset($errors['db_port']) ? ' is-invalid' : '' ?>" name="db_port" value="<?= e((string) ($s['db']['port'] ?? 3306)) ?>"><div class="invalid-feedback"><?= e($errors['db_port'] ?? '') ?></div></div>
                        <div class="col-md-12"><label class="form-label">Database name</label><input type="text" class="form-control<?= isset($errors['db_name']) ? ' is-invalid' : '' ?>" name="db_name" value="<?= e($s['db']['name'] ?? 'sitewatch') ?>"><div class="invalid-feedback"><?= e($errors['db_name'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Username</label><input type="text" class="form-control<?= isset($errors['db_user']) ? ' is-invalid' : '' ?>" name="db_user" value="<?= e($s['db']['user'] ?? 'root') ?>" autocomplete="off"><div class="invalid-feedback"><?= e($errors['db_user'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Password</label><input type="password" class="form-control" name="db_password" value="" autocomplete="new-password"></div>
                        <div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="db_create" id="db_create" value="1" checked><label class="form-check-label" for="db_create">Create the database if it does not exist (requires privileges; on cPanel create it in MySQL Databases first)</label></div></div>
                    </div>
                    <input type="hidden" name="target" value="1">
                    <div class="d-flex gap-2 mt-4"><button type="submit" name="action" value="back" class="btn btn-light" formnovalidate>Back</button><button type="submit" class="btn btn-primary flex-grow-1">Test connection &amp; continue</button></div>
                </form>

            <?php elseif ($step === 3): ?>
                <h1>Database tables</h1>
                <p class="lead-text">SiteWatch will now create its tables in <span class="code-inline"><?= e($s['db']['name'] ?? '') ?></span> (server <?= e($s['db_version'] ?? '') ?>). Existing SiteWatch tables are kept.</p>
                <form method="post"><?= $csrf->field() ?><input type="hidden" name="action" value="tables">
                    <input type="hidden" name="target" value="2">
                    <div class="d-flex gap-2"><button type="submit" name="action" value="back" class="btn btn-light">Back</button><button type="submit" class="btn btn-primary flex-grow-1">Create tables</button></div>
                </form>

            <?php elseif ($step === 4): ?>
                <h1>Administrator account</h1>
                <p class="lead-text">This account signs in to the monitoring dashboard.</p>
                <form method="post" novalidate><?= $csrf->field() ?><input type="hidden" name="action" value="admin">
                    <div class="row g-3">
                        <div class="col-md-6"><label class="form-label">Full name</label><input type="text" class="form-control<?= isset($errors['admin_name']) ? ' is-invalid' : '' ?>" name="admin_name" value="<?= e($s['admin']['name'] ?? '') ?>"><div class="invalid-feedback"><?= e($errors['admin_name'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control<?= isset($errors['admin_email']) ? ' is-invalid' : '' ?>" name="admin_email" value="<?= e($s['admin']['email'] ?? '') ?>" autocomplete="username"><div class="invalid-feedback"><?= e($errors['admin_email'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Password (min. 10 characters)</label><input type="password" class="form-control<?= isset($errors['admin_password']) ? ' is-invalid' : '' ?>" name="admin_password" autocomplete="new-password"><div class="invalid-feedback"><?= e($errors['admin_password'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Confirm password</label><input type="password" class="form-control<?= isset($errors['admin_password_confirmation']) ? ' is-invalid' : '' ?>" name="admin_password_confirmation" autocomplete="new-password"><div class="invalid-feedback"><?= e($errors['admin_password_confirmation'] ?? '') ?></div></div>
                    </div>
                    <input type="hidden" name="target" value="3">
                    <div class="d-flex gap-2 mt-4"><button type="submit" name="action" value="back" class="btn btn-light" formnovalidate>Back</button><button type="submit" class="btn btn-primary flex-grow-1">Continue</button></div>
                </form>

            <?php elseif ($step === 5): ?>
                <h1>Application settings</h1>
                <p class="lead-text">These can be changed later under Settings.</p>
                <form method="post" novalidate><?= $csrf->field() ?><input type="hidden" name="action" value="settings">
                    <div class="row g-3">
                        <div class="col-md-6"><label class="form-label">Application name</label><input type="text" class="form-control<?= isset($errors['app_name']) ? ' is-invalid' : '' ?>" name="app_name" value="<?= e($s['app']['name'] ?? 'SiteWatch') ?>"><div class="invalid-feedback"><?= e($errors['app_name'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Application URL</label><input type="url" class="form-control<?= isset($errors['app_url']) ? ' is-invalid' : '' ?>" name="app_url" value="<?= e($detectedUrl) ?>"><div class="invalid-feedback"><?= e($errors['app_url'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Timezone</label><select class="form-select<?= isset($errors['app_timezone']) ? ' is-invalid' : '' ?>" name="app_timezone"><?php foreach (DateTimeZone::listIdentifiers() as $tz): ?><option value="<?= e($tz) ?>"<?= ($s['app']['timezone'] ?? 'Asia/Karachi') === $tz ? ' selected' : '' ?>><?= e($tz) ?></option><?php endforeach; ?></select><div class="invalid-feedback"><?= e($errors['app_timezone'] ?? '') ?></div></div>
                        <div class="col-md-6"><label class="form-label">Default monitoring interval</label><select class="form-select" name="default_check_interval"><?php foreach ([1, 2, 5, 10, 15, 30] as $i): ?><option value="<?= $i ?>"<?= (int) ($s['app']['interval'] ?? 5) === $i ? ' selected' : '' ?>><?= $i ?> minute<?= $i === 1 ? '' : 's' ?></option><?php endforeach; ?></select></div>
                    </div>
                    <input type="hidden" name="target" value="4">
                    <div class="d-flex gap-2 mt-4"><button type="submit" name="action" value="back" class="btn btn-light" formnovalidate>Back</button><button type="submit" class="btn btn-primary flex-grow-1">Finish installation</button></div>
                </form>

            <?php else: ?>
                <h1>Installation complete</h1>
                <p class="lead-text"><?= e($appName) ?> is ready. Two things remain on the server:</p>
                <div class="alert alert-info">
                    <b>1. Configure the cron job</b> (every minute). In cPanel → Cron Jobs, or with <span class="code-inline">crontab -e</span>:
                    <div class="copy-box mt-2">* * * * * php <?= e($cronPath) ?> &gt;/dev/null 2&gt;&amp;1</div>
                    <div class="fs-12 mt-2">Replace <span class="code-inline">php</span> with the full PHP 8.2 binary path if needed (e.g. <span class="code-inline">/usr/local/bin/php</span> or <span class="code-inline">/opt/cpanel/ea-php82/root/usr/bin/php</span>). See README.</div>
                </div>
                <div class="alert alert-warning"><b>2. Protect the installer.</b> The file <span class="code-inline">storage/install.lock</span> was created, so this wizard is now disabled. For extra safety delete <span class="code-inline">install.php</span> from the server.</div>
                <a href="<?= e(($s['app']['url'] ?? $baseUrl) . '/login.php') ?>" class="btn btn-primary btn-lg w-100">Sign in to <?= e($appName) ?></a>
                <?php $session->remove('_install'); ?>
            <?php endif; ?>
        <?php endif; ?>
        </div>
        <div class="auth-footer">SiteWatch · PHP <?= e(PHP_VERSION) ?></div>
    </div>
</div>
</body>
</html>
